runtime: python311

automatic_scaling:
  max_instances: 10  # 필요에 따라 1~20+로 조정 가능
  min_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

handlers:
  - url: /.*
    script: auto
